name: Validate with Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            composer:2 \
            composer validate --strict

      - name: Cache Composer packages (host-side only)
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            composer:2 \
            composer install --prefer-dist --no-progress

      # Optional: Run test suite (you must make sure dependencies like phpunit exist in image or vendor/)
      # - name: Run test suite
      #   run: |
      #     docker run --rm \
      #       -v ${{ github.workspace }}:/app \
      #       -w /app \
      #       php:8.2-cli \
      #       vendor/bin/phpunit
