name: Validate with Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            php:8.2-cli \
            composer validate --strict

      - name: Cache Composer packages (not used inside container)
        # Optional: only works if host cache is mounted into container
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies in container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            php:8.2-cli \
            sh -c "apt-get update && apt-get install -y unzip git && \
                   curl -sS https://getcomposer.org/installer | php && \
                   php composer.phar install --prefer-dist --no-progress"

      # Optional: Run test suite (you must make sure dependencies like phpunit exist in image or vendor/)
      # - name: Run test suite
      #   run: |
      #     docker run --rm \
      #       -v ${{ github.workspace }}:/app \
      #       -w /app \
      #       php:8.2-cli \
      #       vendor/bin/phpunit
